### ISSUE TITLE
docker image for jumpserver

### ISSUE THREAD

**Issue by xiaopeng163** [ibuler/jumpserver#16]
I saw the install guide from http://laoguang.blog.51cto.com/6013350/1636273
it's very clear but i suggest we should also provide a docker image of our `jumpserver` for whom want to have a quick try.

for example, gitlab https://hub.docker.com/r/gitlab/gitlab-ce/

**Comment by ibuler** [comment]
I would like do that many times. But I have little knowledge of docker.
So would you like do that project ?

**Comment by xiaopeng163** [comment]
I can't promise you, but I will try.  :)

**Comment by ibuler** [comment]
Thank you for help, I‘m very glad to tell you the new version is in development.
