### ISSUE TITLE
配置文件不可以设置复杂密码

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahahahahaha** [ibuler/jumpserver#24]
#coding: utf8

[base]
ip = 11.11.11.11
port = 80
key = 88aaaf7ffe3c6c04

[db]
host = 127.0.0.1
port = 3306
user = devjump
password = EPU1c]$Z\!zb"6V\1[[QS3ML!@EQ
database = jumpserver

[ldap]
ldap_enable = 1
host_url = ldap://127.0.0.1:389
base_dn = dc=xxx, dc=org
root_dn = cn=dev,dc=xxx,dc=org
root_pw = I+`EC{pd/!@s=zj]@'*/c{`CWD QQ,*U

[websocket]
web_socket_host = 103.249.28.21:3000

[mail]
email_host = smtp.qq.com
email_port = 25
email_host_user =
email_host_password =
email_use_tls = False

----------------------------------------------------
设置为上面密码。python manage.py syncdb 命令会提示账户登录错误信息。

**Comment by ibuler** [comment]
那肯定是账号密码不对，是不是太复杂了
