### ISSUE TITLE
文件zzjumpserver.sh中为什么做了无意义的输出？

### ISSUE THREAD

**Issue by tiancaiamao** [ibuler/jumpserver#27]
```sh
if [ "$USER" == "admin" ] || [ "$USER" == "root" ] || [ "$USER" == "" ];then
    echo ""
else
```

我不知道这个文件是否默认安装的在/etc/profile.d的，同事放在了那里
导致登陆shell输入不干净
在rsync的时候会出现 protocol version mismatch -- is your shell clean?

**Comment by tiancaiamao** [comment]
http://serverfault.com/questions/267154/protocol-version-mismatch-is-your-shell-clean

**Comment by ibuler** [comment]
rsync时可能这个用户进不了bash, 可以酌情改一下这个脚本，目的是普通用户开机运行 connect.py脚本，上面echo 是为了让大家知道哪些用户被排除了

**Comment by tiancaiamao** [comment]
意思就是admin和root用户可以直接登陆，而普通用户会走connect.py脚本咯
你看改成echo -n是否合适？
echo ""会输出一个换行符，污染了输出。我是把本地的改掉了

**Comment by ibuler** [comment]
应该没问题，完成更改可以pull a request
