### ISSUE TITLE
bug（next.py）

### ISSUE THREAD

**Issue by kevinzu007** [ibuler/jumpserver#28]
ubuntu 14.04
在安装jumpserver过程中，出现以下提示：
>请再次输入管理员密码: [5Lov@wife]: 
>id: admin: no such user
用户不能成功创建，修改一下文件即可
jumpserver/install/next.py文件中：
```sh
os.system('id %s &> /dev/null || useradd %s' % (self.admin_user, self.admin_user))
```
改为：
```sh
os.system('bash  -c "id %s &> /dev/null || useradd %s"' % (self.admin_user, self.admin_user))
```
即：添加bash  -c " "即可修正

**Comment by ibuler** [comment]
这个问题不具有通用性，ubuntu安装使用还会遇到别的问题
