### ISSUE TITLE
[Error]_fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:

### ISSUE THREAD

**Issue by apanly** [ibuler/jumpserver#30]
我的是centos 6.5 安装过程出现
File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'

解决办法：
$ pip uninstall pycrypto
$ yum erase python-crypto
$ yum install python-crypto python-paramiko

**Comment by ibuler** [comment]
https://github.com/ibuler/jumpserver/wiki/FAQs
见 6
