### ISSUE TITLE
No valid Key exchange context

### ISSUE THREAD

**Issue by junjiemars** [ibuler/jumpserver#32]
I met 'No valid Key exchange context' error and cannot login into jumpserver. 
1) first, I logon jumpserver website, then download private rsa key from server;
2) use ssh-keygen and the passphrase to generate the public key;
3) try to 
```shell
ssh -v -i my-rsa.pub username@jumpserver
```

JumpServer is Cool, but I don't know how to play with it, and I need some help, thank you.

**Comment by ibuler** [comment]
You needn't generate public key.
1. down the private key
2. use ssh tool(like xshell, securecrt) import the private key
    or on mac
    # chmod 600 pkey
   # ssh-add  pkey 
      then type the key pass
3. ssh connect jumpserver
