### ISSUE TITLE
Update database error tip 

### ISSUE THREAD

**Issue by boy6585948** [ibuler/jumpserver#35]
File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xE6\\x9C\\xBA\\xE6\\x88\\xBF' for column 'name' at row 1")
#CentOS 7.0

**Comment by barryz** [comment]
这个应该是mysql数据库字符集设置问题 character-set-server=utf-8

**Comment by ibuler** [comment]
楼上说的对
