### ISSUE TITLE
CentOS 6.x 系统中自带的 python-crypto 2.0.1 与 jumpserver 中 Crypto.PublicKey.RSA.generate() 的接口不兼容

### ISSUE THREAD

**Issue by zhong** [ibuler/jumpserver#4]
环境：
操作系统版本：CentOS release 6.6 (Final)
PyCrypto 版本：python-crypto-2.0.1-22.el6.x86_64

问题现象：
在 jumpserver 的 Web UI 中添加用户，报错如下：
添加用户 hello 失败 `generate_c() takes at least 2 arguments (1 given)`

问题描述：
juser/view.py 中 `gen_ssh_key()` 函数中 `key = RSA.generate(length)`，此方法与 CentOS 6.x 系统中 PyCrypto 中该接口不兼容。PyCrypto 2.0.1 版本中要求提供提供随机数生成器函数： `generate = generate_c(bits, randfunc, progress_func=None)`

**Comment by ibuler** [comment]
是的和自带的不兼容，具体操作见 http://bbs.jumpserver.org/read.php?tid=2&fid=2

**Comment by zhong** [comment]
@ibuler 多谢答复
