### ISSUE TITLE
磁盘数据超过6个或者更多后显示异常

### ISSUE THREAD

**Issue by lg31415** [ibuler/jumpserver#40]
磁盘数目超过6个后，数据库字段溢出。
需要调整数据库和代码的两个地方：
jasset/models.py:    disk = models.CharField(max_length=8192, blank=True, null=True, verbose_name=u'硬盘')
数据字段改写成：
 alter table jasset_asset modify column disk varchar(8192) ;

**Comment by ibuler** [comment]
已经修复
