### ISSUE TITLE
websocket 模块存在安全隐患

### ISSUE THREAD

**Issue by losswei** [ibuler/jumpserver#8]
单独启动: node index.js

打开浏览器输入：localhost:3000

在控制台输入:
$.getScript("http://localhost:3000/socket.io/socket.io.js");
var socket = io.connect('ws://localhost:3000');
socket.emit('login', {userid:"test", filename:"/Users/kelly/word.txt"});
socket.on('message',function(obj){console.log(obj.content)});

详细：
![image](https://cloud.githubusercontent.com/assets/4577514/7839900/6d83985a-04c7-11e5-87da-98ea356f06fa.png)

**Comment by ibuler** [comment]
收到bug，此bug需要在nodejs上添加认证才可完成，正在想办法

**Comment by ibuler** [comment]
Bug已解决，请测试！！

**Comment by losswei** [comment]
有测试过能否用相对路径绕过目录限制吗?

**Comment by ibuler** [comment]
路径已经限制到 /opt/jumpserver/logs/connect里面了，不过还没做更深的认证

**Comment by losswei** [comment]
感觉还是不行啊,这样可以通过相对路径绕过去, 换成os.path.abspath会好点.

**Comment by ibuler** [comment]
你更新代码了吗？

**Comment by losswei** [comment]
当然
```python
def node_auth(request):
    username = request.POST.get('username', ' ')
    seed = request.POST.get('seed', ' ')
    filename = request.POST.get('filename', ' ')
    user = User.objects.filter(username=username, password=seed)
    auth = 1
    if not user:
        auth = 0
    if not filename.startswith('/opt/jumpserver/logs/connect/'):
```
你使用的是`startswith`担心,用户采用"/opt/jumpserver/logs/connect/../../../jumpserver.conf"的方式.

**Comment by ibuler** [comment]
明白了，非常感谢！
